#!/usr/bin/env bash

REPO_PATH="$HOME/personal/dev"
cd "$REPO_PATH" || exit 1

if [ -n "$(git status --porcelain)" ]; then
    git add .
    git commit -m "dev-commit: $(date +'%Y-%m-%d %H:%M:%S')"
    git push origin main
else
    echo "No changes to commit."
fi
