set-option -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"
set-option -ga terminal-overrides ",*256col*:Tc"
set-option -ga terminal-overrides ",*:RGB"
set-option  -g focus-events on
set -s escape-time 0
set -g mouse on

# UTF-8 support
set -gq status-utf8 on
set -gq utf8 on


# Update environment variables
set-option -g update-environment "DISPLAY SSH_ASKPASS SSH_AUTH_SOCK SSH_AGENT_PID SSH_CONNECTION WINDOWID XAUTHORITY TERM LANG LC_ALL LC_CTYPE"

# set -g status-style 'bg=#1c1d24 fg=#5eacd3'
set -g status-style 'bg=#141415 fg=#cdcdcd'
set -g base-index 1
unbind C-b
set-option -g prefix C-Space
bind C-Space send-prefix

# vim style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# set vi-mode
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind-key c new-window -c "#{pane_current_path}"


# keybindings
# tmux sessionizer
bind-key -r f new-window ~/dev-env/scripts/muxify
bind-key -n C-g new-window -c "#{pane_current_path}" "~/dev-env/scripts/open_git"
# run-shell ~/personal/dev/config/tmux/plugins/resurrect.tmux
